name: gif-browser
version: 0.1

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -threaded
  - -rtsopts
  - '"-with-rtsopts=-N -T"'

dependencies:
  - JuicyPixels
  - base
  - bytestring
  - gloss
  - gloss-juicy

executables:
  gif-browser:
    main: Main.hs
    source-dirs:
      - src
